layout object page
ilBury/FreestyleApp pull request #2
Opened 2024-02-28 12:59 UTC by ilBury

2024-03-04 15:45 UTC, ho-thach-nguyen-lx commented on webapp/controller/ObjectPage.controller.js
> +	"sap/base/strings/formatMessage"
You should not define format message in controller file. You can import it within xml file. Please check in details the examples I've provided in notion

2024-03-04 15:47 UTC, ho-thach-nguyen-lx commented on webapp/controller/ObjectPage.controller.js
> +        getSuppliersAddress: function(data) {
Dont repeat yourself principle (DRY):
The logic of getSuppliersName and getSuppliersAddress are quite similar. Can we reuse it?

2024-03-04 15:48 UTC, ho-thach-nguyen-lx commented on webapp/manifest.json
> +					"pattern": "objectPage/{productId}",
as we discussed, the url should represent the idea of a page, not its floorplan

2024-03-04 15:48 UTC, ho-thach-nguyen-lx commented on webapp/manifest.json
> +				"objectPage": {
Same here. Not object page but rather productDetailsPage or something like that

2024-03-04 15:52 UTC, ho-thach-nguyen-lx commented on webapp/view/ObjectPage.view.xml
> +                title="General information"
No hardcoded text

2024-03-04 15:52 UTC, ho-thach-nguyen-lx commented on webapp/view/ObjectPage.view.xml
> +                            pattern: 'yyyy-MM-ddTHH:mm:ss'
This is not quite good because people from different countries see dates differently.
Please remove it and find another way how to format date.

2024-03-04 15:53 UTC, ho-thach-nguyen-lx commented on webapp/view/ObjectPage.view.xml
> +                                            path: '',
This looks quite weird and hard to read. Can we somehow change it?

2024-03-04 16:02 UTC, ho-thach-nguyen-lx commented
This is not quite correct 
<img width="913" alt="Screenshot 2024-03-04 alle 19 01 32" src="https://github.com/ilBury/FreestyleApp/assets/160735908/97fafad9-31a9-4138-80ca-22515ce0d83b">

2024-03-04 16:03 UTC, ho-thach-nguyen-lx commented
Let's use inverted object status for availability field

2024-03-04 16:04 UTC, ho-thach-nguyen-lx requested changes
Hi,
Please have a look at the comments above.
In case of any questions please don't hesitate to ask

2024-03-05 09:38 UTC, ho-thach-nguyen-lx commented on webapp/view/ObjectPage.view.xml
> +                                            path: '',
"Supplier": [{ "id": "1" }, {id: "2"}],

2024-03-06 07:21 UTC, ho-thach-nguyen-lx commented on webapp/controller/ProductDetails.controller.js
> +		formatDate: function(sDate) {
I don't see you use this method anywhere

2024-03-06 07:24 UTC, ilBury commented on webapp/controller/ProductDetails.controller.js
> +		formatDate: function(sDate) {
oh, Sorry, I forgot delete this. I just added it when try to solve issue with date

2024-03-06 07:28 UTC, ho-thach-nguyen-lx commented
I found a small bug. When you open this link http://localhost:8080/index.html#/product/666 the page is empty, but it should redirect user to 404 error page

2024-03-06 07:29 UTC, ho-thach-nguyen-lx requested changes
Just minor fixes needs to be delivered

2024-03-06 07:29 UTC, ho-thach-nguyen-lx commented on webapp/view/ProductDetails.view.xml
> +
Empty lines make it harder to read the code.
Please remove them. 
I suggest you to use vs code plugin 'xml tools', so you don't need format xml files manually

2024-03-06 08:23 UTC, ilBury commented
> Just minor fixes needs to be delivered

I pushed changes

2024-03-06 09:47 UTC, merged