use smart controls
ilBury/FreestyleApp pull request #9
Opened 2024-04-03 12:34 UTC by ilBury

2024-04-03 13:05 UTC, ho-thach-nguyen-lx reviewed
Red: add i18n 

Blue: Hide this field. You always need to hide technical fields from the end user.
They give them no info and sense

<img width="655" alt="Снимок экрана 2024-04-03 в 16 03 21" src="https://github.com/ilBury/FreestyleApp/assets/160735908/bf90a150-87e6-41e7-9bff-3cc61868f3ad">

2024-04-03 13:05 UTC, ho-thach-nguyen-lx commented on webapp/view/ListReport.view.xml
> +						<!-- <fb:FilterBar id="filterbar" persistencyKey="myPersKey" useToolbar="false" >
Remove comments if they're not needed

2024-04-03 13:05 UTC, ho-thach-nguyen-lx commented on webapp/view/ListReport.view.xml
> +	xmlns:smartFilterBar="sap.ui.comp.smartfilterbar"
Do not forget to remove redundant namespaces.

2024-04-03 13:05 UTC, ho-thach-nguyen-lx commented on webapp/view/ListReport.view.xml
> +						entitySet="Products" enableAutoColumnWidth="true" enableExport="false"
Let's enable exporting, personalisation (aka p13n)

2024-04-03 13:05 UTC, ho-thach-nguyen-lx commented on webapp/view/ListReport.view.xml
> +									text="{@i18n>CreateText}"
Don't use @i18n
It's intended to be used in annotations only. 
Tomorrow I will explain to you what the diff between i18n and @i18n is

2024-04-03 13:05 UTC, ho-thach-nguyen-lx commented on webapp/annotations/annotation.xml
> +                <Annotation Term="Common.ValueListWithFixedValues" />
Let's make supplier filter as value help dialog, not combobox.
The reason why it shouldn't be combobox is there could be plenty suppliers. Therefore combobox is not suitable for this case, but value help dialog with table inside it.

2024-04-03 13:05 UTC, ho-thach-nguyen-lx commented on webapp/annotations/annotation.xml
> +                <Annotation Term="Common.ValueListWithFixedValues" />
Combobox is intended to be used when you're sure there couldn't be more than 100 records and data structure is simple.
Category filter is the best case to use combobox but not suppliers.

2024-04-08 12:00 UTC, ilBury reviewed
As I said before I have a weird problem with select in objectPage and because of this we can't create/edit a new category and supplier with product.

2024-04-10 09:24 UTC, ho-thach-nguyen-lx commented
Created At, Updated At should be read only

2024-04-10 09:24 UTC, ho-thach-nguyen-lx commented
Hide column
<img width="586" alt="Снимок экрана 2024-04-10 в 12 24 00" src="https://github.com/ilBury/FreestyleApp/assets/160735908/752d1584-9b1c-4c0d-8784-ab48e3e1671f">

2024-04-10 09:25 UTC, ho-thach-nguyen-lx commented
Add text
<img width="584" alt="Снимок экрана 2024-04-10 в 12 24 57" src="https://github.com/ilBury/FreestyleApp/assets/160735908/186056cb-033a-429d-82c7-5a9a69e21729">

2024-04-10 09:36 UTC, ho-thach-nguyen-lx commented
Because of odata v2, smart controls and other things some files became redundant such as suppliers.json, fragments folder and so on.
Please delete them if they are truly redundant

2024-04-15 08:53 UTC, ho-thach-nguyen-lx requested changes

2024-04-15 08:53 UTC, ho-thach-nguyen-lx commented on webapp/controller/ListReport.controller.js
> +			const sProductId = sPath.match(sNumberRegex)[0];
Get product id from the data, not path

2024-04-15 08:53 UTC, ho-thach-nguyen-lx commented on webapp/controller/ProductDetails.controller.js
> +						/* const sSupplierId = this.getView().getBindingContext().getObject("Supplier")?.ID
Remove comments

2024-04-15 08:53 UTC, ho-thach-nguyen-lx commented on webapp/controller/ProductDetails.controller.js
> +				/* this.byId("idSmartCategoryField"),
comments

2024-04-15 08:53 UTC, ho-thach-nguyen-lx commented on webapp/controller/ProductDetails.controller.js
>  						message: "Should be required",
i18n

2024-04-15 08:53 UTC, ho-thach-nguyen-lx commented on webapp/controller/ProductDetails.controller.js
> +			/* const newCategoryURI = this.byId("idCategoriesSelect").getSelectedItem().getBindingContext().getPath();
How many times i should repeat that no comments should left if they're meaningless?

2024-04-15 08:53 UTC, ho-thach-nguyen-lx commented on webapp/controller/ProductDetails.controller.js
> +
Why do we need these line breaks? It makes code review much harder.
If you want to beautify the code, use prettier. Automate what can be automated

2024-04-15 08:53 UTC, ho-thach-nguyen-lx commented on webapp/controller/ProductDetails.controller.js
> +				success: (oData) => {
Where is error handler?

2024-04-15 08:53 UTC, ho-thach-nguyen-lx commented on webapp/view/ListReport.view.xml
> +						enableAutoBinding="true" header="Products"
add i18n

2024-04-15 08:53 UTC, ho-thach-nguyen-lx commented on webapp/view/ListReport.view.xml
> +									text="{@i18n>CreateText}"
use @i18n in annotations only

2024-04-16 13:26 UTC, ho-thach-nguyen-lx requested changes

2024-04-16 13:26 UTC, ho-thach-nguyen-lx commented on webapp/controller/ProductDetails.controller.js
> +					if(bIsCreateMode) {
where is error handler?

2024-04-16 13:26 UTC, ho-thach-nguyen-lx commented on webapp/controller/ProductDetails.controller.js
> +				success: () => {
what will happen if the request fails?

2024-04-16 13:26 UTC, ho-thach-nguyen-lx commented on webapp/manifest.json
> +					"disableHeadRequestForToken": true
What does it solve?

2024-04-17 07:01 UTC, merged